<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">
<link rel="stylesheet" href="/theme-assets/vendors/css/vendors.min.css">
<link rel="stylesheet" href="/theme-assets/css/bootstrap.css">
<link rel="stylesheet" href="/theme-assets/css/bootstrap-extended.css">
<link rel="stylesheet" href="/theme-assets/css/colors.css">
<link rel="stylesheet" href="/theme-assets/css/components.css">
<link rel="stylesheet" href="/theme-assets/css/themes/dark-layout.css">
<link rel="stylesheet" href="/theme-assets/css/themes/bordered-layout.css">
<link rel="stylesheet" href="/theme-assets/css/themes/semi-dark-layout.css">
<link rel="stylesheet" href="/theme-assets/css/core/menu/menu-types/vertical-menu.css">
<link rel="stylesheet" href="/theme-assets/assets/css/style.css">
